import os

DEV_SECRET_KEY = os.getenv('DEV_SECRET_KEY')

MYSQL_HOST = os.getenv('MYSQL_HOST')
MYSQL_PORT = os.getenv('MYSQL_PORT')
MYSQL_PASSWORD_DEV = os.getenv('MYSQL_PASSWORD_DEV')
MYSQL_DB_DEV = os.getenv('MYSQL_DB_DEV')
MYSQL_USER_DEV = os.getenv('MYSQL_USER_DEV')

SQLALCHEMY_DATABASE_URI = f'mysql://{MYSQL_USER_DEV}:{MYSQL_PASSWORD_DEV}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DB_DEV}?ssl-mode=REQUIRED'